name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable, nightly ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Download deps
      run: sudo apt update && sudo apt install -y clang libclang-dev libopencv-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
